// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toxhaqxbumqqcfqushxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRveGhhcXhidW1xcWNmcXVzaHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDA2NDcsImV4cCI6MjA2MzA3NjY0N30._TmBSSlskikpZ0HN7AoRcNVIBeaMUVJ-Qs-3tl-zbdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);